package nene.backend.task.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

// TODO: Concept - DTO (Data Transfer Object)
//  A DTO is a simple class used to TRANSFER data between layers.
//  Why not just use the Entity directly?
//  1. We don't want to expose internal fields (like id, timestamps) in requests.
//  2. We can validate what the CLIENT sends us.
//  3. We control exactly what data the CLIENT receives back.

public class TaskDto {

    // TODO: Concept - REQUEST DTO (what the client SENDS to us)
    //  This defines the shape of the JSON body the client must send.
    //  Example JSON: { "title": "Fix login bug", "description": "...", "dueDate": "2025-02-01" }
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class CreateRequest {

        // TODO: Concept - VALIDATION ANNOTATIONS
        //  @NotBlank means: not null AND not empty AND not just whitespace.
        //  If the client sends an empty title, Spring will automatically
        //  return a 400 Bad Request with the error message below.
        @NotBlank(message = "Title is required")
        private String title;

        private String description;

        @NotNull(message = "Due date is required")
        private LocalDate dueDate;

        private String priority;  // "LOW", "MEDIUM", "HIGH"
    }

    // TODO: Concept - UPDATE REQUEST DTO
    //  Similar to CreateRequest, but allows updating status too.
    //  All fields are optional in an update — only send what you want to change.
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class UpdateRequest {

        @NotBlank(message = "Title is required")
        private String title;

        private String description;

        private LocalDate dueDate;

        private String priority;  // "LOW", "MEDIUM", "HIGH"

        private String status;    // "CREATED", "IN_PROGRESS", "DONE"
    }

    // TODO: Concept - RESPONSE DTO (what we SEND BACK to the client)
    //  We choose exactly which fields the client sees.
    //  Notice: we include id and timestamps here (auto-generated by the server).
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Response {
        private UUID id;
        private String title;
        private String description;
        private String status;
        private String priority;
        private LocalDate dueDate;
        private LocalDateTime createdAt;
        private LocalDateTime updatedAt;
    }
}
